app/Main.hs, resources/PureScmTest.Fib.corefn.json, resources/PureScmTest.Fib.purs, src/Language/PureScript/Scheme/CodeGen/AST.hs, src/Language/PureScript/Scheme/CodeGen/Optimizer.hs, src/Language/PureScript/Scheme/CodeGen/Printer.hs, src/Language/PureScript/Scheme/CodeGen/Transpiler.hs
- Add `PureScmTest.Fib` test module
- Add to AST: Identifier, Cond, Application and Lambda
- Extend Printer to emit Identifier, Cond, Application and Lambda
- Extend Transpiler to (sort of) handle Identifier, Cond, Application and Lambda
- Add simple optimizer to specialize sum and subtraction
Now we can compile Fibonacci, but the name resolution produces a wrong identifier for the recursive call.
=> Make it compile fibonacci

resources/PureScmTest.FunctionMultipleMatch.corefn.json, resources/PureScmTest.FunctionMultipleMatch.purs, src/Language/PureScript/Scheme/CodeGen/Transpiler.hs
- Handle NullBinder
- Handle multiple binders
Now this code
```
foo 0 0 = 0
foo 0 1 = 1
foo 1 0 = 10
foo _ 2 = 2
foo 3 _ = 30
foo _ _ = 50
```
will translate into
```
(define foo
(lambda (v)
(lambda (v1)
(cond
((and (= v 0) (= v1 0)) 0)
((and (= v 0) (= v1 1)) 1)
((and (= v 1) (= v1 0)) 10)
((and #t (= v1 2)) 2)
((and (= v 3) #t) 30)
((and #t #t) 50)))))
```
Maybe TODO (if it's the case make new cards):
- Optimize away `(and val #t)` into `val`
- Optimize away `(and #t #t)` into `#t` or `else`.
I think it's easier to handle those cases in the optimizer instead of emitting the optimized code straight away. What do you think?
This should close #16
=> Handle multiple binders in case expression

src/Language/PureScript/Scheme/CodeGen/AST.hs, src/Language/PureScript/Scheme/CodeGen/Optimizer.hs, src/Language/PureScript/Scheme/CodeGen/Printer.hs, src/Language/PureScript/Scheme/CodeGen/SExpr.hs, src/Language/PureScript/Scheme/CodeGen/Scheme.hs, src/Language/PureScript/Scheme/CodeGen/Transpiler.hs
Currently we're using AST for stuff that's clearly not syntax: Cond, Lambda, Define.
Going a step further, Scheme has no syntax other than primitive literals (symbols, numbers, strings) and lists. That's exactly what we call S-Expressions. (One could say S-Expressions also include dotted pairs `'(x . y)`, but since that's can be achieved with just `(cons 'x 'y)` we're not including them.)
What we lose: barely nothing. Using Cond to express `cond` expressions gives us no advantage, and the new design can handle conds with a final else expression in a clearer way. Using Lambda to express an anonymous function doesn't allow us to express functions with multiple parameters, which are not a thing in PureScript but they're definitely present in Scheme.
Overall it can give us more flexibility …
=> Change AST To S-Expression

src/Language/PureScript/Scheme/CodeGen/Transpiler.hs, test/resources/purescript/src/PureScheme/Test/Let/LambdasInFunction.purs, test/resources/purescript/src/PureScheme/Test/Let/TopLevelLambdas.purs, test/resources/purescript/src/PureScheme/Test/Let/TopLevelValues.purs, test/resources/purescript/src/PureScheme/Test/Let/ValuesInFunction.purs, test/resources/scheme/PureScheme.Test.Let.LambdasInFunction.sls, test/resources/scheme/PureScheme.Test.Let.TopLevelLambdas.sls, test/resources/scheme/PureScheme.Test.Let.TopLevelValues.sls, test/resources/scheme/PureScheme.Test.Let.ValuesInFunction.sls
Close #14 
I could not add the following test since the compiler complained about Accessor being not implemented
```
module PureScheme.Test.Let.LambdasInFunction where
import Prelude
foo x y =
let
add a b = x + y
sub a b = x - y
in
add (sub x y) (add x y)
```
```
Compiling PureScheme.Test.Let.LambdasInFunction to test/resources/scheme/PureScheme.Test.Let.LambdasInFunction.sls                                                           
purescm-exe: Not implemented                                                          
CallStack (from HasCallStack):                                                        
error, called at src/Language/PureScript/Scheme/CodeGen/Transpiler.hs:60:9 in purescm-0.0.1-7jQQA0FNYBqCYCmhGNiK2q:Language.PureScript.Scheme.CodeGen.Transpiler
```
=> Handle let expressions

src/Language/PureScript/Scheme/CodeGen/Transpiler.hs, test/resources/purescript/src/PureScheme/Test/Guard/Take.purs, test/resources/scheme/PureScheme.Test.Binder.Guard/lib.sls, test/resources/scheme/PureScheme.Test.Guard.GCD/lib.sls, test/resources/scheme/PureScheme.Test.Guard.Min/lib.sls, test/resources/scheme/PureScheme.Test.Guard.Take/lib.sls
Fix #63 as per title. Since there can be multiple guards for each condition branch of a `case`, we duplicate them when merging the conditions. This can be seen in action in the `PureScheme.Test.Binder.Guard` test.
We include the failing example from #63 as a test here, and it now reads correct:
```scheme
(scm:define
take
(scm:letrec*
((go
(scm:lambda (acc)
(scm:lambda (v)
(scm:lambda (v1)
(scm:cond
((scm:fx<? v 1) acc)
((scm:eq? (scm:car v1) (scm:quote Nil)) acc)
((scm:eq? (scm:car v1) (scm:quote Cons))
(((go ((Cons (scm:vector-ref (scm:cdr v1) 0)) acc))
(scm:fx- v 1))
(scm:vector-ref (scm:cdr v1) 1)))
(scm:else (scm:error #f "Failed pattern match"))))))))
(go Nil)))
```
=> Unify the two conds generated by case binders and guards

src/Main.purs, src/PureScript/Backend/Chez/Convert.purs, src/PureScript/Backend/Chez/Syntax.purs, test-snapshots/snapshots-output/Snapshot.Function.ss, test-snapshots/snapshots-output/Snapshot.Literals.ss, test/Main.purs
Begins to address #74
I'm following the spec I summarized in https://github.com/JordanMartinez/purs-backend-cs/blob/master/chez-scheme-eBNF.md
I haven't fully implemented the types for the `expr`, but this is at least a better start than what we had.
I haven't removed the other code PureFunctor wrote in case we want to reuse parts of that.
=> Refactor syntax towards spec; pretty-print things

spago.dhall, src/PureScript/Backend/Chez/Convert.purs, src/PureScript/Backend/Chez/Runtime.purs, src/PureScript/Backend/Chez/Syntax.purs, test-snapshots/packages.dhall, test-snapshots/snapshots-input/Snapshot.Branch.purs, test-snapshots/snapshots-input/Snapshot.Comparison.purs, test-snapshots/snapshots-output/Snapshot.Branch.ss, test-snapshots/snapshots-output/Snapshot.Comparison.ss, test-snapshots/snapshots-output/Snapshot.Function.ss, test-snapshots/snapshots-output/Snapshot.Import.Impl.ss, test-snapshots/snapshots-output/Snapshot.Import.ss, test-snapshots/snapshots-output/Snapshot.Literals.ss, test-snapshots/spago.dhall, test/Main.purs
This PR implements code generation for `Branch`, `PrimOp`, and `Fail` (partially, see comment in source). This also adds a runtime module which provides functions that are otherwise not present in the standard library.
=> Implement Branch, PrimOp, and Fail; add runtime module

packages.dhall, spago.yaml, src/PureScript/Backend/Chez/Convert.purs, src/PureScript/Backend/Chez/Syntax.purs, test-snapshots/src/snapshots-input/Snapshot.Constructor.purs, test-snapshots/src/snapshots-input/Snapshot.ConstructorAccessor.purs, test-snapshots/src/snapshots-output/Snapshot.Constructor.ss, test-snapshots/src/snapshots-output/Snapshot.ConstructorAccessor.ss
This PR is a rework of #85.
Constructors are implemented in the following way:
- If their arity is zero, the structure representing the constructor
is a simple symbol. E.g. if the constructor is Foo, the symbol is
'Foo. A constructing function with the same name as the constructor
is also produced alongside a predicate function whose name has a
trailing question mark (respectively Foo and Foo?).
- If the arity is one, Scheme records are used. The record type name
is the constructor name with a trailing dollar character (e.g. Foo$).
Constructing and predicate functions are provided by the
define-record-type form and follow the same conventions as
described in the previous point. The form takes also care of
producing accessor functions whose name is Ctor-valueN, where Ctor
is the …
=> Implement data constructors codegen

src/PureScript/Backend/Chez/Constants.purs, src/PureScript/Backend/Chez/Convert.purs, src/PureScript/Backend/Chez/Runtime.purs, src/PureScript/Backend/Chez/Syntax.purs, test/Main.purs
Fixes #87.
Replaces all usages of `"scm:something"` with `scmPrefixed "something"` to ensure any references to chezscheme library values/functions actually work.
Does the same thing for "rt:"
=> Use scmPrefixed or rtPrefixed

src/PureScript/Backend/Chez/Syntax.purs
Remove unneeded `uncons`ing
I noticed this while working on #98. Depends on #98.
=> Speed up curried app printing

src/PureScript/Backend/Chez/Constants.purs, src/PureScript/Backend/Chez/Convert.purs, test-snapshots/src/snapshots-input/Snapshot.PrimUndefined.purs, test-snapshots/src/snapshots-output/Snapshot.PrimUndefined.ss
This converts `PrimUndefined` to a constant symbol `'undefined`. The other choice was `(void)` but using a constant allows us to know that it came from PS code (or potentially Chez Scheme FFI)
=> Convert PrimUndefined

.github/workflows/ci.yml
This changes the cache key to depend on spago.yaml files instead of  *.dhall files from old Spago
=> Fix cache key in CI

src/PureScript/Backend/Chez/Convert.purs, src/PureScript/Backend/Chez/Runtime.purs, src/PureScript/Backend/Chez/Syntax.purs, test-snapshots/spago.yaml, test-snapshots/src/snapshots-input/Snapshot.Literals.Record.purs, test-snapshots/src/snapshots-output/Snapshot.ArrayIndex.ss, test-snapshots/src/snapshots-output/Snapshot.Comparison.ss, test-snapshots/src/snapshots-output/Snapshot.Function.ss, test-snapshots/src/snapshots-output/Snapshot.Literals.Record.ss, test-snapshots/src/snapshots-output/Snapshot.Literals.ss, test-snapshots/src/snapshots-output/Snapshot.PrimUndefined.ss, test-snapshots/src/snapshots-output/Snapshot.Prime.ss, vendor/purs/runtime/srfi/private/check-arg.sls, vendor/purs/runtime/srfi/private/define-values.chezscheme.sls, vendor/purs/runtime/srfi/private/vanish.sls
This PR integrates the added SRFIs to the runtime. Arrays and records are now represented by SRFI 214 and SRFI 125 respectively. This is the second half of #135.
=> Integrate SRFIs to runtime

src/PureScript/Backend/Chez/Convert.purs, test-snapshots/src/snapshots-input/Snapshot.Literals.Number.purs, test-snapshots/src/snapshots-output/Snapshot.Literals.Number.ss
Fixes the situation where the backend-optimizer evaluates an expression to JS Infinity, -Infinity or NaN such that those values appear literally in the scheme source. We just generate the correct counterparts for those values in scheme.
Fixes #144
=> Fix codegen for floats

src/PureScript/Backend/Chez/Convert.purs, src/PureScript/Backend/Chez/Runtime.purs, test-snapshots/src/snapshots-output/Snapshot.ArrayIndex.ss
* Fixes array indexing to reference the correct runtime symbol
* Fixes `array-length` reference and adds that to the runtime
=> Fix array-ref and array-length references

test/Main.purs, test/Utils.purs
This refactors the test suite so that it adds the vendor directory to the libdir instead of copying the entire directory over to the test output directory. This is in line with the main CLI.
Also remove comment about runtime files.
=> Add vendor directory to the libdir instead of copying all the files

src/Main.purs, src/PureScript/Backend/Chez/Builder.purs, test/Main.purs, test/Utils.purs
Refactor by adding a common builder helper. This removes some duplication we have, mainly the reading of corefn files. Does not change functionality in any way.
=> Add a common builder helper

src/PureScript/Backend/Chez/Syntax.purs, test-snapshots/spago.yaml, test-snapshots/src/snapshots-output/Snapshot.Literals.Record.ss, test/Utils.purs
Fixes the test suite by doing a few things:
* The runnable tests were not failing the test suite in case an error was throw during library imports. This happens because the `with-exception-handler` doesn't catch those errors that we generate for missing FFI definitions. Now using the `base-exception-handler` which does catch those, which then fails the build correctly.
* Record update codegen was broken because it did not return the updated-in-place record.
* Use a prelude that implements just enough record and semiring to pass the currect test suite. I will update the package ref once the prelude PR is merged (and before merging this).
Pending [prelude PR](https://github.com/purescm/purescript-prelude/pull/2)
=> Fix test suite

src/Main.purs, test/Utils.purs
The build was not completing properly because we never finished the `copyFile`. This was just left out from the node lib upgrade.
=> Fix copyFile

spago.yaml, src/PureScript/Backend/Chez/Convert.purs
`backend-optimizer` [now generates](https://github.com/aristanetworks/purescript-backend-optimizer/pull/98) constructor references with empty arguments instead of generating a `Var`.
=> Upgrade backend-optimizer

flake.lock, flake.nix, index.dev.js, test-snapshots/spago.yaml, test/Main.purs
This updates to the latest Spago, which will compile to corefn all the time, and to js only when the backend is not provided.
We also switch from easy-purescript-nix to purescript-overlay for the nix machinery, as it's generally more up to date.
Closes #161
=> Update to Spago 0.93.14, switch to purescript-overlay

README.md, src/Main.purs
Adds a `run` command that allows you to skip the bundling and just eval `main`.
Adding this mainly to make running test suites in libraries easier. I was considering also adding a `test` command that would compile and run, but since spago can't be used to call `purescm run` and because I'd like to still use `spago` as much as possible the easiest path for now seems to just add a `run` and then in libraries do `spago build && purescm run --main Test.Main`.
=> Add run cmd

src/Main.purs
`spago` passes the output flag to a backend as `--output`.
=> Fix output flag to work with spago

src/PureScript/Backend/Chez/Convert.purs, test-snapshots/src/snapshots-input/Snapshot.EffectRef.purs, test-snapshots/src/snapshots-output/Snapshot.EffectRef.ss
Fix bug where all previous bindings in a do block were dropped if the last `bind` was a `PrimEffect`.
=> Fix bug with PrimEffect

src/PureScript/Backend/Chez/Convert.purs, test-snapshots/src/snapshots-input/Snapshot.EffectRef.purs, test-snapshots/src/snapshots-output/Snapshot.EffectRef.ss
We need to return the value in addition to just setting the value of the box. This is not a super nice fix. I think we should refactor the prim effect stuff so that we get more control over what bindings we create, then we can also compile these to plain unboxed assigment.
Fixes #204
=> Fix primitive assignment effect

CONTRIBUTORS.md, flake.lock, flake.nix
> 24 additions & 51 deletions
There is no need to include a dependency for what is effectively a for loop. Including this dependency will have an effect on all downstream users as they will now have their `flake.lock` infected with this dependency. Considering this is also a smaller diff, there is no value in having flake-utils.
Blue Oak license is simpler & framed less in terms of US law than Apache. If this isn’t okay, then I will force push a `BSD-2-Clause-Patent`--& if that isn’t okay, then I’ll go with `Apache-2.0` like the rest (all of these are permissive with patent clauses… I don’t care _that_ much TBH, but I think Blue Oak is overlooked/underrated).
Contribution link omitted as eventually toastal would like to delete his Microsoft GitHub account once more projects offer …
=> Remove flake-utils

package-sets/1.0.0.json
Update the package-set to link to a monorepo that contains all the forked core libraries for purescm.
~~This monorepo is not yet in the `purescm` org - if you think this change is ok I'll move it to the purescm org.~~ I know there have been discussions of moving the upstream core libs to a monorepo. If that happens we can fork that and rebase our changes on top of that, but meanwhile I'd like to move forward with this.
=> Use monorepo for core packages

package-sets/1.0.0.json, spago.lock, src/PureScript/Backend/Chez/Convert.purs, src/PureScript/Backend/Chez/Syntax.purs, test-snapshots/spago.lock, test-snapshots/spago.yaml, test-snapshots/src/snapshots-input/Snapshot.Literals.Record.ss, test-snapshots/src/snapshots-output/Snapshot.List.ss, test-snapshots/src/snapshots-output/Snapshot.Literals.Record.ss, test-snapshots/src/snapshots-output/Snapshot.Literals.ss, test-snapshots/src/snapshots-output/Snapshot.PrimUndefined.ss, test-snapshots/src/snapshots-output/Snapshot.Prime.ss, vendor/purs/runtime.ss
Using hash-tables is expensive for record literals and records are always so small that assoc lists are just faster. In my benchmarks testing the CST parser this is around 30% faster.
There is no way to allocate a hash-table "statically" so that Chez would allocate a fixed size hash-table - we are currently populating record literals in a loop. There is a scheme solution for static records: scheme records! But we can't use those as we don't have the record types available at compile time.
Update to core libs https://github.com/purescm/purescript-core/pull/1
=> Use assoc lists for records

src/Main.purs
This was a recent change which I'm now reverting. Basically this fixes the case when there is an error during compilation, either when AOT compiling or when compiling as part of the `run` command. I had forgotten why I put these error handlers in there, but it was this case. We should probably add a test suite for the CLI at some point.
=> Return with correct exit code when compilation fails

src/PureScript/Backend/Chez/Builder.purs, src/PureScript/Backend/Chez/Convert.purs
This partly reverts 45bce2e because we can still inline `st` even though `Effect.Ref` is no longer inlined. The result is that `Effect.Ref` is thread-safe but `ST` is not.
This is important performance-wise. We can later improve the ST inlining by removing the `box` indirection and use normal variables.
=> Inline `st`

vendor/purs/runtime/pstring-buffer.ss, vendor/purs/runtime/pstring-test.ss, vendor/purs/runtime/pstring.ss
This optimizes many of the string operations by using a new abstraction called _cursor_ that is much like a Scheme port but that works better for our use cases. Cursor has an imperative API that reduces allocations significantly compared to unconsing.
While removing the uses of `pstring-uncons-code-unit` I also found a bug in both `pstring-index-of` and `pstring-last-index-of` where the match wasn't found at all if the string and pattern shared a longer prefix.
This also changes how we decode code points from the UTF-16 bytevector: we now replace lone surrogates with the Unicode Replacement Character. This way we can implement `cursor-read-char` in terms of `cursor-read-code-point`.
Why not use Scheme ports for fast iteration over String? We could use …
=> Optimize string operations by using a "cursor"

src/Main.purs, test/Utils.purs, vendor/purs/runtime/stack-trace.ss
Prints a stack trace for caught exceptions. It will print something like this:
```
Exception: attempt to apply non-procedure #f
at flexvector-map/index-into! (/home/antti/code/purescm/purescm/vendor/purs/runtime/srfi/:214/impl.sls:322,25)
at f (/home/antti/code/purescm/purescm/vendor/purs/runtime/srfi/:214/impl.sls:340,5)
at pstring-regex-replace-single (/home/antti/code/purescm/purescm/vendor/purs/runtime/pstring.ss:746,29)
at testStringRegex (output/Test.Data.String.Regex/lib.ss:74,50)
at main (output/Test.Data.String.Main/lib.ss:33,15)
```
=> Print a stack trace

package-sets/1.0.0.json
The fork uses Scheme native functions for some folds.
I probably just forgot to add this to the package set previously.
=> Add forked lists package to package set

.github/workflows/ci.yml
Cache the nix artifacts between builds (mostly Chez) and don't install node tools (we use nix after all).
=> Add nix caching for CI

README.md, flake.lock, flake.nix, vendor/purs/runtime/pstring.ss, vendor/purs/runtime/test/pstring-test.ss
Use libicu for case conversions. No error handling yet, and uses the "default" locale.
```
Node:
String.toUpper: { mean = 3.52 μs | stddev = 5.87 μs | min = 2.28 μs | max = 61.39 μs }
Old purescm:
String.toUpper: { mean = 135.52 μs | stddev = 20.98 μs | min = 120.78 μs | max = 278.43 μs }
New purescm:
String.toUpper: { mean = 40.49 μs | stddev = 4.44 μs | min = 38.98 μs | max = 79.51 μs }
```
We are now only one order of magnitude slower than node :)
Fixes #249
=> Use libicu for pstring-upcase and pstring-downcase

vendor/purs/runtime/pstring.ss, vendor/purs/runtime/test/pstring-test.ss
Somehow I had forgotten to update `pstring?` when implementing the rope. I think it was because there was a missing test for `pstring?`.
=> Fix pstring? implementation

src/PureScript/Backend/Chez/Constants.purs, src/PureScript/Backend/Chez/Convert.purs, test-snapshots/src/snapshots-output/Snapshot.Literals.Record.ss, test-snapshots/src/snapshots-output/Snapshot.PrimUndefined.ss
We generated a new symbol each time using `gensym`, but I don't think it's necessary. Now just using `'purs-undefined`.
=> Use the same symbol for `PrimUndefined`

src/PureScript/Backend/Chez/Convert.purs, src/PureScript/Backend/Chez/Printer.purs, src/PureScript/Backend/Chez/Syntax.purs, test-snapshots/src/snapshots-input/Snapshot.Failing.RecursiveBindingGroupLet.purs, test-snapshots/src/snapshots-input/Snapshot.Failing.RecursiveBindingGroupTopLevel.purs, test-snapshots/src/snapshots-input/Snapshot.RecursiveDefinition.purs, test-snapshots/src/snapshots-output/Snapshot.Failing.RecursiveBindingGroupLet.ss, test-snapshots/src/snapshots-output/Snapshot.Failing.RecursiveBindingGroupTopLevel.ss, test-snapshots/src/snapshots-output/Snapshot.RecursiveDefinition.ss, test/Main.purs, vendor/purs/runtime.ss
Implements lazy initialization for top-level recursive bindings. This allows mutually recursive top-level definitions to refer to each other during initialization. It also provides a better runtime error in the case that a definition is referring to itself during initialization. These rarely happen in the wild, especially since we use the optimizer that sometimes inlines away these recursive references. However, if you prevent inlining these happen more often. You can read more about lazy initialization [here](https://github.com/purescript/purescript/blob/0527e71725257bf16a3c7bd5fce608e856a77dae/CHANGELOG.d/breaking_fix-4179.md).
This does _not_ implement lazy initialization for non-top-level bindings. I'd like to do this in a separate PR. And note that the Scheme syntax `letrec*` does …
=> Implement lazy initialization for recursive top level bindings

src/PureScript/Backend/Chez/Convert.purs, test-snapshots/src/snapshots-output/Snapshot.Branch.ss, test-snapshots/src/snapshots-output/Snapshot.ConstructorAccessor.ss, test-snapshots/src/snapshots-output/Snapshot.List.ss, test-snapshots/src/snapshots-output/Snapshot.Prime.ss, vendor/purs/runtime.ss
There are no other failure cases than the failed pattern match case, so instead of handling arbitrary error strings we just use a special runtime function for failed pattern matches. This also cleans up the output nicely.
This is part of a series of refactorings I'm doing to use `StringExpr` only for strings that actually need to be escaped. Then we can have the string escaping only in one place.
=> Use a special runtime function for failed pattern match

src/PureScript/Backend/Chez/Convert.purs, src/PureScript/Backend/Chez/Printer.purs, src/PureScript/Backend/Chez/Syntax.purs
This way we do the printing in one place and don't have to care about how strings are printed when constructing string expressions.
=> Move string printing to the Printer
