purescm/purescm

- app/Main.hs
- package.yaml
- resources/corefn.json
- src/Lib.hs
- src/PureScm/CoreFn.hs
- stack.yaml
> Read `CoreFn` using `FromJson` module from the compiler

- src/PureScm/AST.hs
Implemented:
- Symbol
- Literal
- Lambda
- Function application
> Import unfinished Scheme AST and rendered

- LICENSE.txt
- package.yaml
In the future GPL viralty could be an issue for people using core libraries FFI but until then let's stick to AGPL-3.
> Change license to AGPL-3

- src/Language/PureScript/Scheme/CodeGen/Transpiler.hs
- test/Language/PureScript/Scheme/MakeSpec.hs
- test/resources/PureScmTest.MutuallyRecursiveFunction.corefn.json
- test/resources/PureScmTest.MutuallyRecursiveFunction.purs
- test/resources/PureScmTest.MutuallyRecursiveFunction.sls
> Handle top-level recursive binds

- src/Language/PureScript/Scheme/CodeGen/AST.hs
- src/Language/PureScript/Scheme/CodeGen/Transpiler.hs
- test/Language/PureScript/Scheme/MakeSpec.hs
- test/resources/PureScmTest.GuardedFunction.corefn.json
- test/resources/PureScmTest.GuardedFunction.purs
- test/resources/PureScmTest.GuardedFunction.sls
Should close #23 and make Eris happy.
> Handle guarded CaseAlternatives

- src/Language/PureScript/Scheme/CodeGen/Transpiler.hs
- test/Language/PureScript/Scheme/MakeSpec.hs
- test/resources/PureScmTest.NamedBinder.corefn.json
- test/resources/PureScmTest.NamedBinder.purs
- test/resources/PureScmTest.NamedBinder.sls
> Handle NamedBinder

- src/Language/PureScript/Scheme/CodeGen/Transpiler.hs
- test/resources/scheme/PureScheme.Test.Binder.Named.sls
- test/resources/scheme/PureScheme.Test.Guard.GCD.sls
- test/resources/scheme/PureScheme.Test.Recursion.Fibonacci.sls
- test/resources/scheme/PureScheme.Test.Recursion.Mutual.sls
> Fix local symbols resolution

- src/Language/PureScript/Scheme/CodeGen/Printer.hs
- src/Language/PureScript/Scheme/CodeGen/SExpr.hs
- src/Language/PureScript/Scheme/CodeGen/Transpiler.hs
- test/Language/PureScript/Scheme/CodeGen/PrinterSpec.hs
- test/resources/purescript/src/PureScheme/Test/Literal/StringLiteral.purs
- test/resources/scheme/PureScheme.Test.Literal.StringLiteral.sls
> Handle String literals

- src/Language/PureScript/Scheme/CodeGen/Scheme.hs
- src/Language/PureScript/Scheme/CodeGen/Transpiler.hs
- test/resources/purescript/src/PureScheme/Test/Record/Literal.purs
- test/resources/scheme/PureScheme.Test.Record.Literal.sls
> Handle ObjectLiteral

- src/Language/PureScript/Scheme/CodeGen/Scheme.hs
- src/Language/PureScript/Scheme/CodeGen/Transpiler.hs
- test/resources/purescript/src/PureScheme/Test/Record/UpdateClosedRow.purs
- test/resources/purescript/src/PureScheme/Test/Record/UpdateInLet.purs
- test/resources/purescript/src/PureScheme/Test/Record/UpdateOpenRow.purs
- test/resources/scheme/PureScheme.Test.Record.UpdateClosedRow.sls
- test/resources/scheme/PureScheme.Test.Record.UpdateInLet.sls
- test/resources/scheme/PureScheme.Test.Record.UpdateOpenRow.sls
> Handle ObjectUpdate

- src/PureScript/Backend/Chez/Convert.purs
- test-snapshots/spago.yaml
- test-snapshots/src/snapshots-input/Snapshot.UncurriedFunction.purs
- test-snapshots/src/snapshots-output/Snapshot.UncurriedFunction.ss
The snapshot currently errors because the lib doesn't include the corresponding Scheme FFI file.
> Convert uncurried functions

- src/PureScript/Backend/Chez/Convert.purs
- src/PureScript/Backend/Chez/Syntax.purs
- test-snapshots/spago.yaml
- test-snapshots/src/snapshots-input/Snapshot.Effect.purs
- test-snapshots/src/snapshots-input/Snapshot.Let.purs
- test-snapshots/src/snapshots-output/Snapshot.ConstructorAccessor.ss
- test-snapshots/src/snapshots-output/Snapshot.Effect.ss
- test-snapshots/src/snapshots-output/Snapshot.Let.ss
- test/Main.purs
- test/Utils.purs
This PR implements code generation for the effect variants.
> Implement initial code generation for effect

- spago.yaml
- src/PureScript/Backend/Chez/Convert.purs
- src/PureScript/Backend/Chez/Syntax.purs
- test-snapshots/src/snapshots-input/Snapshot.Literals.String.purs
- test-snapshots/src/snapshots-output/Snapshot.Literals.String.ss
> Fix string literals codegen

- src/PureScript/Backend/Chez/Convert.purs
- test-snapshots/src/snapshots-input/Snapshot.Effect.purs
- test-snapshots/src/snapshots-output/Snapshot.Effect.ss
Closes #116. Should finally unblock #109
> Fix code generation for effect chain

- src/PureScript/Backend/Chez/Convert.purs
- test-snapshots/spago.yaml
- test-snapshots/src/snapshots-input/Snapshot.EffectRef.purs
- test-snapshots/src/snapshots-input/Snapshot.UncurriedFunction.purs
- test-snapshots/src/snapshots-output/Snapshot.EffectRef.ss
- test-snapshots/src/snapshots-output/Snapshot.UncurriedFunction.ss
Closes #122:
This does two things:
1. Implement FFI for `refs`
2. Implement conversion for `PrimEffect`
> Convert PrimEffect

- CONTRIBUTORS.md
- src/PureScript/Backend/Chez/Convert.purs
- test-snapshots/src/snapshots-input/Snapshot.ConstructorAccessor.purs
- test-snapshots/src/snapshots-output/Snapshot.ConstructorAccessor.ss
> Fix references to arity length of one constructors

- spago.yaml
- test-snapshots/src/snapshots-output/Snapshot.EffectRef.ss
Upgrade backend-optimizer. There is a small change in inlining, which seems legit to me.
> Upgrade backend-optimizer

- src/Main.purs
- src/PureScript/Backend/Chez/Builder.purs
- test/Main.purs
Adds the ability to pass `--directives <file>` to the `build` command.
> Add support for directives file

- flake.nix
- spago.yaml
- src/Main.purs
- src/PureScript/Backend/Chez/Builder.purs
- test/Main.purs
- test/Utils.purs
@JordanMartinez there are a lot of breaking changes in the Node libraries and I am not quite sure the changes I did to port to the new API make sense, so I'd appreciate if you could have a look
> Upgrade to package set 41.2.0

- README.md
- package-lock.json
- package.json
* Updates package.json to make it possible to publish an npm package.
* Update README to reflect the correct package name and the fact that this can now actually be installed.
> Update package.json and README

- package-lock.json
- package.json
- spago.yaml
> Bump version to 1.1.0

- package-sets/1.0.0.json
I have tested locally that the test suite compiles with all of these packages.
> Add more packages

- package-lock.json
- package.json
- spago.yaml
> Bump version to 1.3.0

- package-lock.json
- package.json
- spago.yaml
> Bump version to 1.3.1

- package-sets/1.0.0.json
Adds:
* `arrays`
* `ordered-collections`
* `filterable`
> Add `arrays`

- flake.lock
- flake.nix
- package-sets/1.0.0.json
- test-snapshots/spago.yaml
* Upgrade spago
* Use local package set in tests
* Build all packages in tests
* Update record to latest version
> Use local package set

- package-lock.json
- package.json
- spago.yaml
* Add runtime support for strings and regexes
* Compile `Data.List` as native scheme list
> Bump version to 1.4.0

- package-lock.json
- package.json
- spago.yaml
> Bump version to 1.5.0

- package-lock.json
- package.json
- spago.yaml
* Use symbols are record labels
> Bump version to 1.6.0

- flake.lock
- flake.nix
- src/Main.purs
> We are happy with bumping nixpkgs to some stable ref (e.g. 23.11)
-- Issue #219
> Nix inputs bump

- package-lock.json
- package.json
* Fixes bug with exit code from `scheme` commands
> Bump version to 1.8.1

- README.md
- package-lock.json
- package.json
- publish-release.sh
- spago.yaml
Moved some logic from `package.json` to a shell script because it's more easier to understand the steps.
> Dump version to 1.8.2 and add release script

- vendor/purs/runtime/pstring.ss
> Fix `pstring-slice-eq?`

- package.json
- test-runtime.js
Forgot a few places. CI should have failed for this, so need to fix that as well later.
> Fix libdir in a few places
